[package]
name = "oxidized"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
raylib = { git = "https://github.com/raylib-rs/raylib-rs", branch = "unstable", features = [

] }
simplelog = "0.12.2"

[build-dependencies]
fs_extra = "1.3.0"
